# Generated by Django 6.1 on 2026-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
