# Generated by Django 6.0.7 on 2026-08-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_division_alter_class_options'),
        ('students', '0001_initial'),
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, default='10th', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.ForeignKey(blank=True, db_column='division_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.division'),
        ),
        migrations.AddField(
            model_name='student',
            name='division_name',
            field=models.CharField(blank=True, default='A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.8, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='users.user'),
        ),
    ]
