# Generated by Django 6.1 on 2026-08-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_timetable'),
        ('semesters', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='academic_year',
            field=models.CharField(blank=True, default='2025-2026', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='division',
            field=models.ForeignKey(blank=True, db_column='division_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.division'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='semester',
            field=models.ForeignKey(blank=True, db_column='semester_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='semesters.semester'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='student_class',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class'),
        ),
    ]
