# Generated by Django 6.0.7 on 2026-08-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_created_at'),
        ('semesters', '0002_alter_semester_options'),
        ('subjects', '0002_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='departments.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, db_column='semester_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='semesters.semester'),
        ),
    ]
