# Generated by Django 6.1 on 2026-08-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_teachersubject_academic_year_teachersubject_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='division',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='student_class',
        ),
    ]
