# Generated by Django 6.0.7 on 2026-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
    ]
