# Generated by Django 6.1 on 2026-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Siddesh Infotech College', max_length=255)),
                ('system_title', models.CharField(default='Student Attendance Management System', max_length=255)),
                ('academic_year', models.CharField(default='2024 - 2025', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('date_format', models.CharField(default='DD MMM YYYY', max_length=50)),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('theme_mode', models.CharField(default='light', max_length=20)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=20)),
                ('sidebar_style', models.CharField(default='default', max_length=20)),
                ('layout_style', models.CharField(default='modern', max_length=20)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('exam_notifications', models.BooleanField(default=True)),
                ('report_notifications', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.CharField(default='587', max_length=10)),
                ('admin_email', models.EmailField(default='admin@siddeshinfotech.edu.in', max_length=254)),
                ('smtp_password', models.CharField(default='••••••••••••', max_length=255)),
                ('encryption', models.CharField(default='TLS', max_length=20)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(default='daily', max_length=50)),
                ('backup_retention', models.CharField(default='30 days', max_length=50)),
                ('last_backup', models.CharField(default='Never', max_length=100)),
                ('enable_2fa', models.BooleanField(default=False)),
                ('session_timeout', models.BooleanField(default=True)),
                ('password_expiry', models.BooleanField(default=True)),
                ('password_expiry_days', models.CharField(default='90', max_length=10)),
                ('max_login_attempts', models.CharField(default='5', max_length=10)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('permissions_matrix', models.JSONField(blank=True, default=dict)),
                ('min_attendance', models.CharField(default='75%', max_length=10)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('attendance_window', models.CharField(default='09:00 AM', max_length=50)),
                ('late_grace_period', models.CharField(default='15', max_length=10)),
                ('auto_attendance', models.BooleanField(default=False)),
                ('attendance_lock_date', models.CharField(default='2026-08-31', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
