# Generated by Django 6.0.7 on 2026-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(blank=True, default='Admin', max_length=100, null=True),
        ),
    ]
