# Generated by Django 6.0.7 on 2026-07-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='departments.department')),
            ],
            options={
                'db_table': 'branches',
                'managed': True,
            },
        ),
    ]
