# Generated by Django 6.0.7 on 2026-08-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'divisions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch')),
                ('semester', models.ForeignKey(blank=True, db_column='semester_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='semesters.semester')),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
    ]
