# Generated by Django 6.0.7 on 2026-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'divisions',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'managed': True},
        ),
    ]
