# Generated by Django 6.0.7 on 2026-08-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('classes', '0002_division_alter_class_options'),
        ('semesters', '0002_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(blank=True, db_column='semester_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='semesters.semester'),
        ),
    ]
