# Generated by Django 6.1 on 2026-08-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
