# Generated by Django 6.1 on 2026-08-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_reset_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
